---
- hosts: all
  gather_facts: true
  roles:
  # system update & upgrade
  - full-upgrade
  # docker maintenence
  - docker-maintain
  # gitlab maintain
  - gitlab-maintain
  # reboot
  - restart-if-required
