- name: install gitlab runner package
  become: yes
  apt:
    name: gitlab-runner
    state: present
- name: add docker group for runner
  become: yes
  user:
    name: gitlab-runner
    groups: docker
