# main
- name: check if certificate exists - ees-elektro.de
  become: yes
  stat:
    path: '/etc/letsencrypt/live/ees-elektro.de/fullchain.pem'
  register: primary_domain_cert
- name: request certificate if it doesn't exist
  become: yes
  shell: 'certbot certonly --noninteractive --agree-tos --cert-name ees-elektro.de -d ees-elektro.de -m {{ssl_email}} --webroot -w /var/www/certbot/html'
  when: not primary_domain_cert.stat.exists
# www
- name: check if certificate exists - www.ees-elektro.de
  become: yes
  stat:
    path: '/etc/letsencrypt/live/www.ees-elektro.de/fullchain.pem'
  register: www_domain_cert
- name: request certificate if it doesn't exist
  become: yes
  shell: 'certbot certonly --noninteractive --agree-tos --cert-name www.ees-elektro.de -d www.ees-elektro.de -m {{ssl_email}} --webroot -w /var/www/certbot/html'
  when: not www_domain_cert.stat.exists
