# main
- name: check if certificate exists - schmerztherapie-zwickau-janmehner.de
  become: yes
  stat:
    path: '/etc/letsencrypt/live/schmerztherapie-zwickau-janmehner.de/fullchain.pem'
  register: primary_domain_cert
- name: request certificate if it doesn't exist
  become: yes
  shell: 'certbot certonly --noninteractive --agree-tos --cert-name schmerztherapie-zwickau-janmehner.de -d schmerztherapie-zwickau-janmehner.de -m {{ssl_email}} --webroot -w /var/www/certbot/html'
  when: not primary_domain_cert.stat.exists
# www
- name: check if certificate exists - www.schmerztherapie-zwickau-janmehner.de
  become: yes
  stat:
    path: '/etc/letsencrypt/live/www.schmerztherapie-zwickau-janmehner.de/fullchain.pem'
  register: www_domain_cert
- name: request certificate if it doesn't exist
  become: yes
  shell: 'certbot certonly --noninteractive --agree-tos --cert-name www.schmerztherapie-zwickau-janmehner.de -d www.schmerztherapie-zwickau-janmehner.de -m {{ssl_email}} --webroot -w /var/www/certbot/html'
  when: not www_domain_cert.stat.exists
