- name: check if GitLab runner is installed  
  stat: 
    path: /usr/bin/gitlab-runner
  register: gitlab_file
- name: download gitlab runner
  become: yes
  get_url:
    url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb
    dest: /tmp/gitlab-runner_amd64.deb
  when: gitlab_file.stat.exists
- name: install package
  become: yes
  apt:
    deb: /tmp/gitlab-runner_amd64.deb
    autoremove: yes
  when: gitlab_file.stat.exists
